"""Complaint model for MongoDB"""
from datetime import datetime
from typing import Optional, List


def complaint_document(data) -> dict:
    """Create a complaint document for MongoDB"""
    return {
        "complaint_id": None,  # Will be generated by service
        "user_id": data.user_id,
        "district_id": data.district_id,
        "ward_id": data.ward_id,
        "inspector_id": data.inspector_id if hasattr(data, "inspector_id") else None,
        "worker_id": data.worker_id if hasattr(data, "worker_id") else None,
        "complaint_type": data.complaint_type,
        "description": data.description,
        "status": "OPEN",
        "priority": data.priority if hasattr(data, "priority") else "MEDIUM",
        "latitude": data.latitude,
        "longitude": data.longitude,
        "address": data.address if hasattr(data, "address") else None,
        "image_urls": data.image_urls if hasattr(data, "image_urls") else [],
        "proof_images": [],
        "citizen_note": data.citizen_note if hasattr(data, "citizen_note") else None,
        "inspector_note": None,
        "worker_note": None,
        "rejection_reason": None,
        "deadline": data.deadline if hasattr(data, "deadline") else None,
        "created_at": datetime.utcnow(),
        "updated_at": datetime.utcnow(),
        "closed_at": None,
    }


def complaint_history_document(data) -> dict:
    """Create a complaint history document for audit trail"""
    return {
        "complaint_id": data.complaint_id,
        "action": data.action,
        "old_status": data.old_status if hasattr(data, "old_status") else None,
        "new_status": data.new_status if hasattr(data, "new_status") else None,
        "performed_by": data.performed_by,
        "role": data.role,
        "remarks": data.remarks if hasattr(data, "remarks") else None,
        "timestamp": datetime.utcnow()
    }


def complaint_response(doc) -> dict:
    """Format complaint document for API response"""
    if not doc:
        return None
    
    doc["_id"] = str(doc.get("_id", ""))
    return doc
