"""Constants used throughout the application"""

# Default values
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# OTP Configuration
OTP_LENGTH = 6
OTP_VALID_CHARS = "0123456789"

# Token Configuration
TOKEN_TYPE_ACCESS = "access"
TOKEN_TYPE_REFRESH = "refresh"

# Status codes
SUCCESS_CODE = 200
CREATED_CODE = 201
BAD_REQUEST_CODE = 400
UNAUTHORIZED_CODE = 401
FORBIDDEN_CODE = 403
NOT_FOUND_CODE = 404
CONFLICT_CODE = 409
RATE_LIMIT_CODE = 429
INTERNAL_ERROR_CODE = 500

# Default expiry messages
TOKEN_EXPIRE_MESSAGE = "Token has expired"
OTP_EXPIRE_MESSAGE = "OTP has expired"

# Complaint statuses
COMPLAINT_STATUS_PENDING = "PENDING"
COMPLAINT_STATUS_IN_REVIEW = "IN_REVIEW"
COMPLAINT_STATUS_APPROVED = "APPROVED"
COMPLAINT_STATUS_ASSIGNED = "ASSIGNED"
COMPLAINT_STATUS_RESOLVED = "RESOLVED"
COMPLAINT_STATUS_REJECTED = "REJECTED"

VALID_COMPLAINT_STATUSES = [
    COMPLAINT_STATUS_PENDING,
    COMPLAINT_STATUS_IN_REVIEW,
    COMPLAINT_STATUS_APPROVED,
    COMPLAINT_STATUS_ASSIGNED,
    COMPLAINT_STATUS_RESOLVED,
    COMPLAINT_STATUS_REJECTED
]

# User status
USER_STATUS_ACTIVE = "ACTIVE"
USER_STATUS_INACTIVE = "INACTIVE"
USER_STATUS_SUSPENDED = "SUSPENDED"

VALID_USER_STATUSES = [
    USER_STATUS_ACTIVE,
    USER_STATUS_INACTIVE,
    USER_STATUS_SUSPENDED
]
